### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by ServeurpersoCom** [pimoroni/unicornhatmini-python#12]
For text demo :

Traceback (most recent call last):
  File "./text.py", line 7, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'

**Comment by Gadgetoid** [comment]
You should `sudo apt install python3-pil`

(or possibly `python-pil` if you're still on ye olde Python)

When I get a moment, I'll investigate why our installer didn't handle this. Or make the example fail with a useful message!

**Comment by ServeurpersoCom** [comment]
Thanks a lot. because I tried pip install Pillow like I found on stackoverflow and other search without success. I test python3-pil/python-pil next time and close issue

**Comment by Gadgetoid** [comment]
Installing "Pillow" via pip is technically the right answer, but ymmv on Raspberry Pi. If you're lucky you'll get a precompiled package from piwheels, if you're unlucky your Pi will try to compile it- the latter is not a fun experience. 😬

**Comment by ServeurpersoCom** [comment]
apt install python-pil python3-pil work.
From stock image it need git, python-pip and python3-pip for the ./install.sh work
