### ISSUE TITLE
Hat not lighting up / not working

### ISSUE THREAD

**Issue by omgcyrilic** [pimoroni/unicornhatmini-python#14]
just got my unicorn hat mini and I ran the instructions but no LEDs are coming on ... is there a test command to see if the device is connected properly?

I'm using the latest Raspbian OS with latest updates ... 

I ran:
```
sudo raspi-config nonint do_spi 0
git clone https://github.com/pimoroni/unicornhatmini-python
cd unicornhatmini-python
sudo ./install.sh
cd ~/Pimoroni/unicornhatmini/examples
ls
python3 demo.py
```

**Comment by Gadgetoid** [comment]
A side-on and top-down photo to see if it's connected properly may help.

The chips are write-only so there's no way to query to see if it's connected.

Is this the *very* latest Raspberry Pi OS? What does `lsb_release -a` and `uname -a` say?

**Comment by helgibbons** [comment]
Closing this for now but feel free to re-open if you're still having trouble!
