### ISSUE TITLE
Add I2C & SPI troubleshooting to instructions

### ISSUE THREAD

**Issue by yasminjl** [pimoroni/unicornhatmini-python#3]
Hi,
I was installing this for the first time ever on a brand new Pi and encountered some issues getting started. When trying to run the examples I got the below message:

```
File "rainbow.py", line 16, in <module>
    unicornhatmini = UnicornHATMini()
  File "build/bdist.linux-armv6l/egg/unicornhatmini/__init__.py", line 45, in _init_
IOError: [Errno 2] No such file or directory
```

I fixed this by enabling I2C and SPI through `raspi-config`.
Should we add this to the instructions or does it already exist and I missed it?

**Comment by HOD42** [comment]
I really ought to know better by now, but I went through three fresh installs before I realised this!

**Comment by blitmap** [comment]
I am glad I saw this issue, it was not obvious to me!  Thank you! :-)
